# Generated by Django 4.1.2 on 2022-12-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readituser',
            name='email',
        ),
    ]
