# Generated by Django 4.1.2 on 2022-12-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_readituser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readituser',
            name='about_text',
            field=models.CharField(blank=True, default='', help_text='Tell us about yourself', max_length=500, null=True, verbose_name='About'),
        ),
    ]
