# Generated by Django 4.1.5 on 2023-02-07 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0004_submission_upvote_set_alter_upvote_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='downvote_set',
            field=models.ManyToManyField(related_name='downvote_set', through='submissions.Downvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
