# Generated by Django 4.1.5 on 2023-02-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submission_downvote_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='text_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
