# Generated by Django 4.1.2 on 2022-12-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreadits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreadit',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
